export const PYTHON_RUNTIME_HELPERS = [
  `    # Use chronological, unique row positions internally; restore the caller's index on return.`,
  `    original_index = df.index.copy()`,
  `    df = df.reset_index(drop=True).copy()`,
  `    row_order = df.sort_values(["asset", "timestamp"], kind="stable").index.to_numpy()`,
  `    df = df.iloc[row_order].reset_index(drop=True)`,
  ``,
  `    def restore_output(values):`,
  `        if np.ndim(values) == 0:`,
  `            return pd.Series(values, index=original_index)`,
  `        result = values.reindex(df.index).copy() if isinstance(values, (pd.Series, pd.DataFrame)) else pd.Series(values, index=df.index)`,
  `        result.index = row_order`,
  `        return result.sort_index().set_axis(original_index)`,
  ``,
  `    def finite_result(values):`,
  `        if isinstance(values, pd.Series):`,
  `            return values.where(np.isfinite(values))`,
  `        return np.where(np.isfinite(values), values, np.nan) if np.ndim(values) else (values if np.isfinite(values) else np.nan)`,
  ``,
  `    def safe_divide(left, right):`,
  `        with np.errstate(divide="ignore", invalid="ignore", over="ignore"):`,
  `            return finite_result(np.divide(left, right))`,
  ``,
  `    def fill_missing(values, value=0):`,
  `        if isinstance(values, pd.Series):`,
  `            return values.astype(float).fillna(value)`,
  `        return np.where(pd.isna(values), value, values) if np.ndim(values) else (value if pd.isna(values) else values)`,
  ``,
  `    def select_values(condition, when_true, when_false):`,
  `        condition = pd.Series(condition, index=df.index, dtype="boolean")`,
  `        selected = np.where(condition.to_numpy(dtype=bool, na_value=False), when_true, when_false)`,
  `        return pd.Series(selected, index=df.index).where(condition.notna())`,
  ``,
  `    def _rolling(values, window, by, min_samples, operation):`,
  `        return values.groupby(df[by], sort=False).apply(lambda group: group.rolling(window, min_periods=min_samples).apply(operation, raw=True)).reset_index(level=0, drop=True).sort_index()`,
  ``,
  `    def _pair_rolling(left, right, window, by, min_samples, operation):`,
  `        result = pd.Series(np.nan, index=left.index, dtype=float)`,
  `        left_groups = left.groupby(df[by], sort=False)`,
  `        right_groups = right.groupby(df[by], sort=False)`,
  `        for (_, left_group), (_, right_group) in zip(left_groups, right_groups):`,
  `            for offset, index in enumerate(left_group.index):`,
  `                left_window = left_group.iloc[max(0, offset - window + 1):offset + 1]`,
  `                right_window = right_group.iloc[max(0, offset - window + 1):offset + 1]`,
  `                pair = pd.concat([left_window, right_window], axis=1).dropna()`,
  `                if len(pair) >= min_samples:`,
  `                    result.loc[index] = operation(pair.iloc[:, 0].to_numpy(), pair.iloc[:, 1].to_numpy())`,
  `        return result`,
  ``,
  `    def _cross_section(values, by, operation):`,
  `        return values.groupby(df[by], sort=False).transform(operation)`,
  ``,
  `    def shift_by_asset(values, periods=1):`,
  `        return values.groupby(df["asset"], sort=False).shift(periods)`,
  ``,
  `    def pct_change_by_asset(values, periods=1):`,
  `        return safe_divide(values, shift_by_asset(values, periods)) - 1`,
  ``,
  `    def rolling_mean(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.nanmean)`,
  ``,
  `    def rolling_sum(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.nansum)`,
  ``,
  `    def rolling_std(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda values: np.std(values[np.isfinite(values)], ddof=1) if np.isfinite(values).sum() > 1 else np.nan)`,
  ``,
  `    def rolling_min(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.nanmin)`,
  ``,
  `    def rolling_max(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.nanmax)`,
  ``,
  `    def rolling_rank(values, window, by="asset", min_samples=1, descending=True):`,
  `        def rank(sample):`,
  `            current = sample[-1]`,
  `            if not np.isfinite(current):`,
  `                return np.nan`,
  `            sample = sample[np.isfinite(sample)]`,
  `            base = np.count_nonzero(sample < current) if descending else np.count_nonzero(sample > current)`,
  `            equal = np.count_nonzero(sample == current)`,
  `            return (base + (equal + 1) / 2) / len(sample)`,
  `        return _rolling(values, window, by, min_samples, rank)`,
  ``,
  `    def rolling_quantile(values, window, quantile, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: np.nanquantile(sample, quantile))`,
  ``,
  `    def rolling_corr(left, right, window, by="asset", min_samples=1, std_tolerance=0):`,
  `        result = _pair_rolling(left, right, window, by, min_samples, lambda a, b: np.corrcoef(a, b)[0, 1] if len(a) > 1 and np.std(a) > 0 and np.std(b) > 0 else np.nan)`,
  `        flat = (rolling_std(left, window, by, 1) <= std_tolerance) | (rolling_std(right, window, by, 1) <= std_tolerance)`,
  `        return result.mask(flat)`,
  ``,
  `    def rolling_cov(left, right, window, by="asset", min_samples=1):`,
  `        return _pair_rolling(left, right, window, by, min_samples, lambda a, b: np.cov(a, b, ddof=0)[0, 1] if len(a) > 1 else np.nan)`,
  ``,
  `    def rolling_slope(values, window, by="asset", min_samples=1):`,
  `        def slope(sample):`,
  `            valid = np.isfinite(sample)`,
  `            if valid.sum() < 2:`,
  `                return np.nan`,
  `            x = np.arange(len(sample))[valid]`,
  `            y = sample[valid]`,
  `            return np.sum((x - x.mean()) * (y - y.mean())) / np.sum((x - x.mean()) ** 2)`,
  `        return _rolling(values, window, by, min_samples, slope)`,
  ``,
  `    def rolling_rsquare(values, window, by="asset", min_samples=1, std_tolerance=0):`,
  `        def rsquare(sample):`,
  `            valid = np.isfinite(sample)`,
  `            if valid.sum() < 2 or np.std(sample[valid], ddof=1) <= std_tolerance:`,
  `                return np.nan`,
  `            return np.corrcoef(np.arange(len(sample))[valid], sample[valid])[0, 1] ** 2`,
  `        return _rolling(values, window, by, min_samples, rsquare)`,
  ``,
  `    def rolling_argmax(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: int(np.argmax(sample)) + 1)`,
  ``,
  `    def rolling_argmin(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: int(np.argmin(sample)) + 1)`,
  ``,
  `    def rolling_skew(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: pd.Series(sample).skew())`,
  ``,
  `    def rolling_kurt(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: pd.Series(sample).kurt())`,
  ``,
  `    def rolling_residual(values, window, by="asset", min_samples=1):`,
  `        def residual(sample):`,
  `            valid = np.isfinite(sample)`,
  `            if valid.sum() < 2 or not np.isfinite(sample[-1]):`,
  `                return np.nan`,
  `            x = np.arange(len(sample))[valid]`,
  `            y = sample[valid]`,
  `            slope = np.sum((x - x.mean()) * (y - y.mean())) / np.sum((x - x.mean()) ** 2)`,
  `            return sample[-1] - (y.mean() + slope * (len(sample) - 1 - x.mean()))`,
  `        return _rolling(values, window, by, min_samples, residual)`,
  ``,
  `    def cross_sectional_rank(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.rank(method="average", pct=True))`,
  ``,
  `    def cross_sectional_mean(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.mean())`,
  ``,
  `    def cross_sectional_std(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.std(ddof=0))`,
  ``,
  `    def cross_sectional_min(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.min())`,
  ``,
  `    def cross_sectional_max(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.max())`,
  ``,
  `    def cross_sectional_zscore(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: (group - group.mean()) / group.std(ddof=0) if group.std(ddof=0) > 0 else np.nan)`,
  ``,
  `    def cross_sectional_scale(values, by="timestamp"):` ,
  `        return _cross_section(values, by, lambda group: group / group.abs().sum() if group.abs().sum() > 0 else np.nan)`,
  ``,
  `    def cross_sectional_neutralize(values, exposure, by="timestamp"):` ,
  `        result = pd.Series(np.nan, index=values.index, dtype=float)`,
  `        for _, indexes in values.groupby(df[by], sort=False).groups.items():`,
  `            y = values.loc[indexes]`,
  `            x = exposure.loc[indexes]`,
  `            valid = y.notna() & x.notna()`,
  `            if valid.sum() >= 2 and x[valid].nunique() > 1:`,
  `                design = np.column_stack([np.ones(valid.sum()), x[valid].to_numpy()])`,
  `                coefficients = np.linalg.lstsq(design, y[valid].to_numpy(), rcond=None)[0]`,
  `                result.loc[indexes[valid.to_numpy()]] = y[valid].to_numpy() - design @ coefficients`,
  `        return result`,
].join('\n')
