export const PYTHON_RUNTIME_HELPERS = [
  `    def _rolling(values, window, by, min_samples, operation):`,
  `        return values.groupby(df[by], sort=False).apply(lambda group: group.rolling(window, min_periods=min_samples).apply(operation, raw=True)).reset_index(level=0, drop=True).sort_index()`,
  ``,
  `    def _pair_rolling(left, right, window, by, min_samples, operation):`,
  `        result = pd.Series(np.nan, index=left.index, dtype=float)`,
  `        left_groups = left.groupby(df[by], sort=False)`,
  `        right_groups = right.groupby(df[by], sort=False)`,
  `        for (_, left_group), (_, right_group) in zip(left_groups, right_groups):`,
  `            for offset, index in enumerate(left_group.index):`,
  `                left_window = left_group.iloc[max(0, offset - window + 1):offset + 1]`,
  `                right_window = right_group.iloc[max(0, offset - window + 1):offset + 1]`,
  `                pair = pd.concat([left_window, right_window], axis=1).dropna()`,
  `                if len(pair) >= min_samples:`,
  `                    result.loc[index] = operation(pair.iloc[:, 0].to_numpy(), pair.iloc[:, 1].to_numpy())`,
  `        return result`,
  ``,
  `    def _cross_section(values, by, operation):`,
  `        return values.groupby(df[by], sort=False).transform(operation)`,
  ``,
  `    def shift_by_asset(values, periods=1):`,
  `        return values.groupby(df["asset"], sort=False).shift(periods)`,
  ``,
  `    def pct_change_by_asset(values, periods=1):`,
  `        return values / shift_by_asset(values, periods) - 1`,
  ``,
  `    def rolling_mean(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.mean)`,
  ``,
  `    def rolling_sum(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.sum)`,
  ``,
  `    def rolling_std(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda values: np.std(values, ddof=0))`,
  ``,
  `    def rolling_min(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.min)`,
  ``,
  `    def rolling_max(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, np.max)`,
  ``,
  `    def rolling_rank(values, window, by="asset", min_samples=1, descending=True):`,
  `        def rank(sample):`,
  `            current = sample[-1]`,
  `            base = np.count_nonzero(sample < current) if descending else np.count_nonzero(sample > current)`,
  `            equal = np.count_nonzero(sample == current)`,
  `            return (base + (equal + 1) / 2) / len(sample)`,
  `        return _rolling(values, window, by, min_samples, rank)`,
  ``,
  `    def rolling_quantile(values, window, quantile, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: np.quantile(sample, quantile))`,
  ``,
  `    def rolling_corr(left, right, window, by="asset", min_samples=1):`,
  `        return _pair_rolling(left, right, window, by, min_samples, lambda a, b: np.corrcoef(a, b)[0, 1] if len(a) > 1 and np.std(a) > 0 and np.std(b) > 0 else np.nan)`,
  ``,
  `    def rolling_cov(left, right, window, by="asset", min_samples=1):`,
  `        return _pair_rolling(left, right, window, by, min_samples, lambda a, b: np.cov(a, b, ddof=0)[0, 1] if len(a) > 1 else np.nan)`,
  ``,
  `    def rolling_slope(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: np.polyfit(np.arange(len(sample)), sample, 1)[0] if len(sample) > 1 else np.nan)`,
  ``,
  `    def rolling_rsquare(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: np.corrcoef(np.arange(len(sample)), sample)[0, 1] ** 2 if len(sample) > 1 and np.std(sample) > 0 else np.nan)`,
  ``,
  `    def rolling_argmax(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: len(sample) - 1 - int(np.argmax(sample)))`,
  ``,
  `    def rolling_argmin(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: len(sample) - 1 - int(np.argmin(sample)))`,
  ``,
  `    def rolling_skew(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: pd.Series(sample).skew())`,
  ``,
  `    def rolling_kurt(values, window, by="asset", min_samples=1):`,
  `        return _rolling(values, window, by, min_samples, lambda sample: pd.Series(sample).kurt())`,
  ``,
  `    def rolling_residual(values, window, by="asset", min_samples=1):`,
  `        def residual(sample):`,
  `            x = np.arange(len(sample))`,
  `            slope, intercept = np.polyfit(x, sample, 1)`,
  `            return sample[-1] - (slope * x[-1] + intercept)`,
  `        return _rolling(values, window, by, min_samples, residual)`,
  ``,
  `    def cross_sectional_rank(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.rank(method="average", pct=True))`,
  ``,
  `    def cross_sectional_mean(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.mean())`,
  ``,
  `    def cross_sectional_std(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.std(ddof=0))`,
  ``,
  `    def cross_sectional_min(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.min())`,
  ``,
  `    def cross_sectional_max(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: group.max())`,
  ``,
  `    def cross_sectional_zscore(values, by="timestamp"):`,
  `        return _cross_section(values, by, lambda group: (group - group.mean()) / group.std(ddof=0) if group.std(ddof=0) > 0 else np.nan)`,
  ``,
  `    def cross_sectional_scale(values, by="timestamp"):` ,
  `        return _cross_section(values, by, lambda group: group / group.abs().sum() if group.abs().sum() > 0 else np.nan)`,
  ``,
  `    def cross_sectional_neutralize(values, exposure, by="timestamp"):` ,
  `        result = pd.Series(np.nan, index=values.index, dtype=float)`,
  `        for _, indexes in values.groupby(df[by], sort=False).groups.items():`,
  `            y = values.loc[indexes]`,
  `            x = exposure.loc[indexes]`,
  `            valid = y.notna() & x.notna()`,
  `            if valid.sum() >= 2 and x[valid].nunique() > 1:`,
  `                design = np.column_stack([np.ones(valid.sum()), x[valid].to_numpy()])`,
  `                coefficients = np.linalg.lstsq(design, y[valid].to_numpy(), rcond=None)[0]`,
  `                result.loc[indexes[valid.to_numpy()]] = y[valid].to_numpy() - design @ coefficients`,
  `        return result`,
].join('\n')
